# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DoctOPD (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire', '~> 4.4'
  pod 'ReachabilitySwift', '~> 4.3.1'
  pod 'SVProgressHUD'

  #pod 'SwiftyJSON', '~> 4.0'
  # Pods for DoctOPD (iOS)

end
